[build]
  base = "."
  publish = "frontend/dist"
  command = "cd frontend && npm run build"
  functions = "backend/src/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
