[build]
  base = "/"
  publish = "frontend/dist"
  command = "cd frontend && npm run build && cd ../backend && npm run build"
  functions = "backend/functions"

[dev]
  port = 8888

[functions]
  directory = "backend/src/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200