[build]
  base = "/"
  publish = "frontend/dist"
  command = "cd frontend && npm run build && cd ../backend && npm run build"
  functions = "backend/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8888
  port = 5173
  publish = "frontend/dist"

[functions]
  directory = "backend/src/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200